### ISSUE TITLE
Syntax error while running container

### ISSUE THREAD

**Issue by gottfrois** [strofcon/hello_semaphore#2]
I have the following issue when running the container:

```
docker run -p 8888:8888 hello_semaphore
mkdir: created directory '/app/running-config'
Exec: /app/erts-8.0.2/bin/erlexec -noshell -noinput +Bd -boot /app/releases/0.0.1/hello_semaphore -mode embedded -config /app/running-config/sys.config -boot_var ERTS_LIB_DIR /app/erts-8.0.2/../lib -env ERL_LIBS /app/lib -pa /app/lib/hello_semaphore-0.0.1/consolidated -args_file /app/running-config/vm.args -- foreground
Root: /app
/app/erts-8.0.2/bin/erlexec: 1: /app/erts-8.0.2/bin/erlexec: Syntax error: "(" unexpected
```

Any idea what's going on?

**Comment by Lazarus404** [comment]
@gottfrois: this tutorial is OLD!  Try using the latest Elixir (1.3.2 at time of posting) and create a new Phoenix app; `mix phoenix.new hello_semaphore`.  Once you've done that, copy the `Dockerfile` and `docker-compose.yml` files to that new project.  You should then be able to continue as normal.

**Comment by gottfrois** [comment]
Thanks for the answer. This particular issue actually comes from the fact that I run the release compilation on a Mac and that the release runs on a Linux docker image. Googled that and it seems that i'm not the only one in that situation ;)

**Comment by jaysoifer** [comment]
@gottfrois: did you get this to work?

I'm running on the exact same situation: MacOS Sierra, Docker Version 1.12.1.

As per @Lazarus404 instructions, I'm using Elixir 1.3.4 but I'm still getting the same error, while trying to run `docker-compose up`:

`erts-8.1/bin/erlexec: Syntax error: "(" unexpected`

**Comment by gottfrois** [comment]
@jaysoifer it's not specific to semaphore. It's about how releases works on elixir. When you build your release, it compiles the file on the host (your mac) so it uses mac based libraries instead of the required linux libraries where your app will be running.

**Comment by jaysoifer** [comment]
It would be nice if the article (https://semaphoreci.com/community/tutorials/dockerizing-elixir-and-phoenix-applications) had a warning of some sort about this...

**Comment by cboggs** [comment]
@jaysoifer - Oof, I completely missed this issue! Many apologies, turns out I had disabled my email notifications for this repo by some odd happenstance. Anyway, sorry again for having accidentally ignored you!

I've definitely run into something similar trying to run these steps against a CentOS box, which I think I mentioned in a response to one of the comments on the tutorial post. As @gottfrois pointed out, it's an issue with the way exrm handles releases, and is something I hadn't considered when I wrote the tutorial originally. That said, it's clearly a very relevant factor to point out. :-)

I have some other testing to do on OS X as well, and as soon as I can get that done I'll clarify in the tutorial text itself that some of these things might be a bit different depending on the development environment the reader is using.

Thanks so much for the feedback, and I'll certainly make sure I don't disable my notifications for issues again! :-) Take care.

**Comment by jaysoifer** [comment]
@cboggs
Thank you for your attention 😄 

If you manage to insert MacOS specific instructions, I'm sure you're gonna have even more readers. I know this seems kind of obvious, I'm trying to point out that there are not so many Docker/MacOS specific tutorials like these around.
